const express=require('express');const http=require('http');const crypto=require('crypto');const {Server}=require('socket.io');const path=require('path');
const app=express(),server=http.createServer(app),io=new Server(server,{cors:{origin:'*'}});app.use(express.static(path.join(__dirname,'public')));
app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const rooms=new Map();const TTL=6*60*60*1000;
const B=[
['START','start','Lewati START dan ambil Rp200'],['Kemang Avenue','property','Lifestyle • Rp180 • sewa Rp30','ruby',180,30],['Kartu Cinta','card','Ambil kartu dari deck Cinta'],['Senopati Bistro','property','Kuliner • Rp220 • sewa Rp35','ruby',220,35],['Pajak Transaksi','tax','Bayar Rp100 ke bank',null,100],['Menteng Residence','property','Hunian • Rp260 • sewa Rp40','ruby',260,40],['Stasiun Kota','transit','Transportasi • Rp200','gold',200,50],['Kartu Chaos','card','Ambil kartu Chaos'],['SCBD Tower','property','Bisnis • Rp300 • sewa Rp50','emerald',300,50],['Bonus Proyek','bonus','Dapat Rp150'],['Blok M Market','property','Retail • Rp340 • sewa Rp55','emerald',340,55],['PLN Nusantara','utility','Utilitas • Rp150','cyan',150,35],['Cilandak Heights','property','Hunian • Rp380 • sewa Rp65','emerald',380,65],['Bebas Drama','rest','Istirahat. Tidak ada efek.'],['Kartu Cinta','card','Ambil kartu dari deck Cinta'],['Pondok Indah Estate','property','Estate • Rp420 • sewa Rp75','violet',420,75],['Pajak Kekayaan','tax','Bayar Rp140 ke bank',null,140],['Bandung Hub','transit','Transportasi • Rp200','gold',200,50],['Kartu Chaos','card','Ambil kartu Chaos'],['Bali Escape','property','Resort • Rp460 • sewa Rp85','violet',460,85],['Cuan Dadakan','bonus','Dapat Rp200'],['Gading Garden','property','Retail • Rp500 • sewa Rp95','amber',500,95],['Air Bersih PDAM','utility','Utilitas • Rp150','cyan',150,35],['Kartu Cinta','card','Ambil kartu dari deck Cinta'],['Jakarta Prime','property','Premium • Rp560 • sewa Rp110','amber',560,110],['Drama Corner','jail','Skip 1 giliran jika mendarat di sini'],['Kartu Chaos','card','Ambil kartu Chaos'],['Surabaya Central','property','Bisnis • Rp600 • sewa Rp120','indigo',600,120],['Bonus Investor','bonus','Dapat Rp250'],['Stasiun Selatan','transit','Transportasi • Rp200','gold',200,50],['Pajak Gaya Hidup','tax','Bayar Rp160 ke bank',null,160],['Kerajaan Cuan','property','Landmark • Rp700 • sewa Rp150','indigo',700,150]
].map((x,i)=>({i,name:x[0],type:x[1],desc:x[2],group:x[3]||null,price:x[4]||0,rent:x[5]||0}));
const LOVE=[
['Bonus Kencan','Bank memberimu Rp180.','money',180],['Traktir Pasangan','Bayar Rp70 kepada pasangan.','give',70],['Investasi Berhasil','Portofolio naik. Dapat Rp220.','money',220],['Surat Cinta','Dapat Rp100; pasangan bayar Rp50 kepadamu.','romance',100,50],['Jalan-Jalan','Maju 3 petak dan selesaikan petaknya.','move',3],['Kembali ke START','Teleport ke START dan ambil bonus lewat START.','goto',0],['Diskon Properti','Pembelian berikutnya diskon Rp100.','discount',100],['Double Step','Gerakan berikutnya mendapat +2 langkah.','boost',2],['Balik Keadaan','Tukar posisi dengan pasangan.','swapPos'],['Rezeki Tak Terduga','Dapat Rp260.','money',260],['Cinta Bersemi','Pasangan membayar Rp90 kepadamu.','take',90],['Free Pass','Simpan kartu: batal skip/penjara sekali.','pass']
].map(c=>({title:c[0],text:c[1],effect:c[2],value:c[3]||0,other:c[4]||0}));
const CHAOS=[
['Denda Parkir','Bayar Rp90.','pay',90],['Rampok Dompet','Ambil Rp120 dari pasangan.','take',120],['Mundur 2','Mundur 2 petak dan selesaikan efeknya.','back',2],['Freeze','Pasangan kehilangan 1 giliran.','freeze'],['Gaspol','Maju 4 petak dan selesaikan efeknya.','move',4],['Pajak Sultan','Bayar Rp180.','pay',180],['Swap Posisi','Tukar posisi dengan pasangan.','swapPos'],['Cuan Misterius','Dapat Rp200.','money',200],['Chaos Ganda','Maju 2 petak + dapat Rp80.','moveMoney',2,80],['Diskon Gelap','Pembelian berikutnya diskon Rp120.','discount',120],['Ambil Alih','Jika pasangan punya properti, ambil Rp100 darinya.','take',100],['Skip','Pasangan skip giliran berikutnya.','freeze']
].map(c=>({title:c[0],text:c[1],effect:c[2],value:c[3]||0,other:c[4]||0}));
function code(){let c;do c=crypto.randomBytes(3).toString('hex').slice(0,5).toUpperCase();while(rooms.has(c));return c}function tok(){return crypto.randomBytes(20).toString('hex')}
function clean(s){return String(s||'Player').replace(/[<>]/g,'').trim().slice(0,18)||'Player'}function opp(r,i){return r.players[1-i]}function pi(r,s){return r.players.findIndex(p=>p.id===s.id)}
function roomForToken(t){for(const r of rooms.values()){let i=r.players.findIndex(p=>p.token===t);if(i>=0)return[r,i]}return null}
function addLog(r,text,kind='info'){r.log.unshift({id:Date.now()+Math.random(),text,kind});r.log=r.log.slice(0,50)}
function money(p,n){p.money=Math.max(0,p.money+n)}
function rentFor(r,t,p){const prop=r.props.find(x=>x.pos===t.i);let base=t.rent;let same=r.props.filter(x=>x.owner===p.id&&x.group===t.group).length;let mult=prop?.level===3?2:prop?.level===2?1.5:1;return Math.ceil(base*mult*(same>=2?2:1))}
function state(r){return {code:r.code,started:r.started,phase:r.phase,turn:r.turn,winner:r.winner,roll:r.roll,pending:r.pending,lastMove:r.lastMove||null,players:r.players.map(p=>({id:p.id,name:p.name,avatar:p.avatar,money:p.money,pos:p.pos,connected:p.connected,skip:p.skip,boost:p.boost,discount:p.discount,pass:p.pass})),tiles:B,props:r.props,log:r.log,card:r.card||null}}
function emit(r){io.to(r.code).emit('state',state(r))}
function notice(r,text,kind='info'){io.to(r.code).emit('notice',{text,kind})}
function newRoom(){const r={code:code(),started:false,phase:'waiting',turn:0,winner:null,roll:null,pending:null,lastMove:null,moveSeq:0,players:[],props:[],log:[],card:null};rooms.set(r.code,r);return r}
function join(r,s,name,avatar,token){if(r.players.length>=2)return null;const p={id:s.id,name:clean(name),avatar:['♟','♥','♦','♣','★','●'].includes(avatar)?avatar:'♟',money:1800,pos:0,connected:true,skip:0,boost:0,discount:0,pass:0,token:token||tok()};r.players.push(p);s.join(r.code);s.data.room=r.code;s.data.token=p.token;return p}
function move(r,i,steps){const p=r.players[i];const old=p.pos;const path=[];const dir=steps>=0?1:-1;for(let k=1;k<=Math.abs(steps);k++){const next=(old+dir*k+B.length*4)%B.length;path.push(next)}let np=(old+steps+B.length*4)%B.length;if(steps>0&&np<old){money(p,200);addLog(r,`${p.name} melewati START dan menerima Rp200.`,'money')}p.pos=np;r.moveSeq=(r.moveSeq||0)+1;r.lastMove={seq:r.moveSeq,playerId:p.id,from:old,to:np,path};return B[np]}
function moveBack(r,i,steps){return move(r,i,-Math.abs(steps))}
function transfer(r,a,b,n){n=Math.min(n,Math.max(0,a.money));money(a,-n);money(b,n);return n}
function maybeWin(r){for(const p of r.players)if(p.money<=0){r.winner=r.players[1-r.players.indexOf(p)].id;r.phase='gameover';r.pending=null;notice(r,`${p.name} kehabisan uang. Permainan berakhir.`,'danger');return true}return false}
function resolve(r,i,depth=0){if(depth>3)return;const p=r.players[i],t=B[p.pos];r.pending=null;r.phase='resolving';
 if(t.type==='start'){money(p,200);notice(r,`${p.name} mendarat di START: +Rp200`,'money')}
 else if(t.type==='bonus'){money(p,t.price||150);notice(r,`${p.name} mendapat bonus Rp${t.price||150}.`,'money')}
 else if(t.type==='tax'){money(p,-t.price);notice(r,`${p.name} membayar pajak Rp${t.price}.`,'danger')}
 else if(t.type==='rest'){notice(r,`${p.name} sedang istirahat di ${t.name}.`,'info')}
 else if(t.type==='jail'){p.skip=1;notice(r,`${p.name} masuk Drama Corner dan skip 1 giliran.`,'danger')}
 else if(t.type==='property'||t.type==='transit'||t.type==='utility'){
   const prop=r.props.find(x=>x.pos===t.i);
   if(prop&&prop.owner!==p.id){const owner=r.players.find(x=>x.id===prop.owner);const rent=t.type==='property'?rentFor(r,t,p):t.type==='transit'?Math.max(50,50*r.props.filter(x=>x.owner===owner.id&&x.type==='transit').length):Math.min(180,Math.floor(p.money*0.1));const paid=transfer(r,p,owner,rent);notice(r,`${p.name} membayar Rp${paid} sewa kepada ${owner.name}.`,'danger');}
   else if(!prop){r.pending={kind:'buy',player:i,pos:t.i};r.phase='buying';notice(r,`${t.name} tersedia seharga Rp${t.price}.`,'buy');return}
   else notice(r,`${t.name} milik ${p.name}.`,'info');
 }
 else if(t.type==='card'){const deck=t.desc.includes('Cinta')?LOVE:CHAOS;const c=deck[Math.floor(Math.random()*deck.length)];r.card={...c,deck:t.desc.includes('Cinta')?'CINTA':'CHAOS'};applyCard(r,i,c,depth);return}
 if(maybeWin(r))return;r.phase='action';emit(r)}
function applyCard(r,i,c,depth){const p=r.players[i],o=opp(r,i);r.card={...c};notice(r,`${p.name} membuka kartu ${c.title}.`,'card');switch(c.effect){case'money':money(p,c.value);break;case'pay':money(p,-c.value);break;case'give':transfer(r,p,o,c.value);break;case'take':transfer(r,o,p,c.value);break;case'romance':money(p,c.value);transfer(r,o,p,c.other);break;case'discount':p.discount=c.value;break;case'boost':p.boost+=c.value;break;case'freeze':o.skip+=1;break;case'swapPos':[p.pos,o.pos]=[o.pos,p.pos];break;case'pass':p.pass+=1;break;case'goto':p.pos=c.value;break;case'move':move(r,i,c.value);resolve(r,i,depth+1);return;case'back':moveBack(r,i,c.value);resolve(r,i,depth+1);return;case'moveMoney':move(r,i,c.value);money(p,c.other);resolve(r,i,depth+1);return}if(maybeWin(r))return;r.phase='action';emit(r)}
function nextTurn(r){r.pending=null;r.card=null;r.phase='rolling';r.turn=1-r.turn;const p=r.players[r.turn];if(p.skip>0){p.skip--;notice(r,`${p.name} terkena skip. Giliran dilewati.`,'danger');return nextTurn(r)}emit(r)}
function actionAllowed(r,s){const i=pi(r,s);return i>=0&&r.started&&r.phase==='rolling'&&r.turn===i&&r.phase!=='gameover'}
io.on('connection',s=>{s.on('create',({name,avatar}={})=>{const r=newRoom();join(r,s,name,avatar);emit(r);s.emit('room',{code:r.code,token:s.data.token})});s.on('join',({code:raw,name,avatar,token}={})=>{const code=String(raw||'').trim().toUpperCase();let r=rooms.get(code);if(!r){s.emit('errorMsg','Room tidak ditemukan.');return}let restored=token&&roomForToken(token);if(restored&&restored[0]===r){const p=r.players[restored[1]];const oldId=p.id;for(const prop of r.props)if(prop.owner===oldId)prop.owner=s.id;if(r.winner===oldId)r.winner=s.id;p.id=s.id;p.connected=true;s.join(r.code);s.data.room=r.code;s.data.token=p.token;emit(r);return}if(r.players.length>=2){s.emit('errorMsg','Room sudah penuh.');return}const p=join(r,s,name,avatar);if(p)s.emit('room',{code:r.code,token:p.token});emit(r)});
s.on('start',()=>{const r=rooms.get(s.data.room);if(!r||r.players.length!==2||r.started)return;r.started=true;r.phase='rolling';addLog(r,'Permainan dimulai. Giliran pemain pertama.','system');notice(r,'Permainan dimulai! Pemain pertama lempar dadu.','system');emit(r)});
s.on('roll',()=>{const r=rooms.get(s.data.room);if(!r||!actionAllowed(r,s))return;const i=pi(r,s),p=r.players[i];let d=1+Math.floor(Math.random()*6);d+=p.boost;p.boost=0;r.roll=d;notice(r,`${p.name} mendapatkan ${d} langkah.`,'dice');move(r,i,d);r.phase='moving';emit(r);setTimeout(()=>{if(rooms.has(r.code)){resolve(r,i);}},650)});
s.on('buy',()=>{const r=rooms.get(s.data.room);if(!r||r.phase!=='buying'||r.turn!==pi(r,s)||!r.pending)return;const i=pi(r,s),p=r.players[i],t=B[r.pending.pos];if(t.type!=='property'&&t.type!=='transit'&&t.type!=='utility')return;let price=Math.max(0,t.price-p.discount);if(p.money<price){notice(r,'Uang tidak cukup untuk membeli.','danger');return}p.money-=price;p.discount=0;r.props.push({pos:t.i,owner:p.id,name:t.name,type:t.type,group:t.group,level:1});notice(r,`${p.name} membeli ${t.name} seharga Rp${price}.`,'buy');r.phase='action';r.pending=null;emit(r)});
s.on('skipBuy',()=>{const r=rooms.get(s.data.room);if(!r||r.phase!=='buying'||r.turn!==pi(r,s))return;r.pending=null;r.phase='action';emit(r)});
s.on('endTurn',()=>{const r=rooms.get(s.data.room);if(!r||r.phase!=='action'||r.turn!==pi(r,s))return;nextTurn(r)});
s.on('upgrade',({pos}={})=>{const r=rooms.get(s.data.room);const i=pi(r,s);if(!r||r.phase!=='action'||r.turn!==i)return;const prop=r.props.find(x=>x.pos===Number(pos)&&x.owner===r.players[i].id&&x.type==='property');if(!prop||prop.level>=3)return;const t=B[prop.pos],cost=Math.ceil(t.price*(0.35));if(r.players[i].money<cost)return; r.players[i].money-=cost;prop.level++;notice(r,`${r.players[i].name} meningkatkan ${t.name} ke Lv.${prop.level}.`,'buy');emit(r)});
s.on('restart',()=>{const r=rooms.get(s.data.room);if(!r||r.players.length!==2)return;r.started=false;r.phase='waiting';r.turn=0;r.winner=null;r.roll=null;r.pending=null;r.card=null;r.lastMove=null;r.moveSeq=(r.moveSeq||0)+1;r.props=[];r.log=[];for(const p of r.players){p.money=1800;p.pos=0;p.connected=true;p.skip=0;p.boost=0;p.discount=0;p.pass=0;}addLog(r,'Meja di-reset. Menunggu START dari salah satu pemain.','system');emit(r)});
s.on('disconnect',()=>{const r=rooms.get(s.data.room);if(!r)return;const i=pi(r,s);if(i>=0){r.players[i].connected=false;addLog(r,`${r.players[i].name} terputus. Menunggu reconnect...`,'danger');emit(r)}})});
setInterval(()=>{const now=Date.now();for(const [c,r] of rooms)if(!r.players.some(p=>p.connected)&&now-r.log.slice(-1)[0]?.id>TTL)rooms.delete(c)},60*60*1000);
app.get('/health',(req,res)=>res.json({ok:true,rooms:rooms.size}));const PORT=process.env.PORT||3000;server.listen(PORT,()=>console.log('Cinta & Cuan v4.2.1 on '+PORT));
